define bass = Character("Ms. Bass", color="#ffffff")
define uceng = Character("Uceng", color="#ffffff")
define lele = Character("Lele", color="#ffffff")
define gator = Character("Gator", color="#ffffff")

define salmon = Character("Mrs. Salmon", color="#ffffff")
define sal = salmon
define arowana = Character("Mr. Wana", color="#ffffff")
define aro = arowana
define tinykrill = Character("Tiny Krill", color="#ffffff")
define ghost = Character("Ghostfish", color="#ffffff")
define shrimp = Character("Mantis Shrimp", color="#ffffff")

define dunge = Character("Dunge", color="#ffffff")
define hawk = Character("Hawk", color="#ffffff")
define teto = Character("Teto", color="#ffffff")
define bunny = Character("Sea Bunny", color="#ffffff")
define emp = Character("Empress Crustacean VIII")

define scy = Character("Scyllarus", color="#ffffff")
define rin = Character("Chief Rin", color="#ffffff")
define leo = Character("Leo", color="#ffffff")
define ori = Character("Orin", color="#ffffff")
define stall1 = Character("Stall Keeper", color="#ffffff")
define stall2 = Character("Booth Master", color="#ffffff")
define planktons = Character("Planktons", color="#ffffff")
define fish1 = Character("Cheering Fish", color="#ffffff")
define fish2 = Character("Excited Fish", color="#ffffff")

define scy_fake = Character("Mr. Larus???", color="#90e0ef")
define cory_fake = Character("Mr. Cory???", color="#ffd166")
define leo_fake = Character("Miss Leo???", color="#ffb4a2")
define ban = Character("The Banished One", color="#c77dff")
define ban_unknown = Character("???", color="#9d4edd")
define mama = Character("Mama", color="#ffffff")
define mama_fake = Character("Mama???", color="#e0aaff")
define papa = Character("Papa", color="#ffffff")
